name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_call' && 'main' || github.ref }}

      - name: Setup Deno 🔧
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linters and formatter checks 🚨
        run: |
          deno lint
          deno fmt --check
          deno check mod.ts
