name: sync

on:
  schedule:
    # At minute 32 (picked randomly) past every 12th hour
    - cron: 32 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: sync
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Deno 🔧
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run sync 🔁
        run: deno run --allow-net --allow-env --allow-read ./mod.ts
        env:
          DISCORD_EVENTS_SYNC_DISCORD_GUILD_ID: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_GUILD_ID }}
          DISCORD_EVENTS_SYNC_DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_BOT_TOKEN }}
          DISCORD_EVENTS_SYNC_DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_APPLICATION_ID }}
          DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_CALENDAR_ID: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_CALENDAR_ID }}
          DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_API_KEY: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_API_KEY }}
